#!/bin/bash

#SBATCH --job-name="test"
#SBATCH --partition=shared
#SBATCH --time 08:00:00
#SBATCH --output=vasp.out
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=64
#SBATCH --account=tg-dmr160007

module purge
module load cpu/0.15.4
module load  intel/19.1.1.217
module load slurm
module load intel-mkl/2019.1.144
module load intel-mpi/2019.8.254
mpirun $VASP > stdout 
